# Basic data types.
Note: Print your results after each question.

In [1]:
# Integers
x = 3

# TODO: Print the type of x
print(type(x))

# TODO: Addition. Add 1 to x and print the result
x += 1
print(x)

# TODO: Subtraction. Subtract 1 from x and print the result
x -= 1
print(x)
# TODO: Multiplication. Multiply x with 2 and print the result
x*=2
print(x)

# TODO: Exponentiation. Print the square of x
print(x**2)


<class 'int'>
4
3
6
36


In [2]:
# Float
y = 2.5

# TODO: Print the type of y
print(type(y))

# TODO: Use operator *= to double the value of y and print y
y *= 2
print(y)

# TODO: Use operator += to add 3 to y and print y
y += 3
print(y)


<class 'float'>
5.0
8.0


In [3]:
# Strings
s = "hello"
# TODO: Capitalize the above string and print it
s = s.capitalize()
print(s)

# TODO: Convert the string to uppercase and print it
s = s.upper()
print(s)
# TODO: Right-justify the string, padding with 2 spaces print it;
print(s.rjust(7))
# TODO: Center the string, padding with 2 spaces print it;
print(s.center(7))
# TODO: Replace all instances of letter l  with "(ell)" and print it;
s = s.lower()
temp = ""
for i in range(len(s)):
  if s[i] == 'l':
    temp += "ell"
  else:
    temp += s[i]
print(temp)

str = " world "
# TODO: Strip leading and trailing whitespace in the above string and print
str = str.strip()
print(str)


Hello
HELLO
  HELLO
 HELLO 
heellello
world


# Containers

In [4]:
# Lists
list1 = [1,2,3,4]
# TODO: Change the 3rd element to "foo" and print list1
list1[2] = "foo"
print(list1)

list2 = ["bar"]
# TODO: Append list2 to list1 and print the result
list1.append(list2)
print(list1)

# TODO: Add list2 to list1 using extend and print the result
list1.extend(list2)
print(list1)
# TODO: Remove last element in list1 using pop and print list1
list1.pop()
print(list1)


[1, 2, 'foo', 4]
[1, 2, 'foo', 4, ['bar']]
[1, 2, 'foo', 4, ['bar'], 'bar']
[1, 2, 'foo', 4, ['bar']]


In [5]:
#Slicing
nums = list(range(5))
# TODO: Print a slice from index 2 to 4 (exclusive)
print(nums[2:4])

# TODO: Print a slice from index 2 to 4 (inclusive)
print(nums[2:5])

# TODO: Obtain the last two items using a negative index
last = nums[-1]
secondLast = nums[-2]
print(last)
print(secondLast)
# TODO: Create a new list = [8,9] and overwrite it to the slice from index 2 to 4 (exclusive)
nums2 = [8,9]
nums[2:4] = nums2
print(nums)


[2, 3]
[2, 3, 4]
4
3
[0, 1, 8, 9, 4]


In [6]:
# Loops
nums = [0, 1, 2, 3, 4]
squares = []

# TODO: Append squares of each element in nums to squares using for loop
for x in nums:
  squares.append(x**2)
print(squares)
####

animals = ['cat', 'dog', 'monkey']

# TODO: Print index and elements in the list using enumerate and for loop
for index, animal in enumerate(animals):
    print(f"Index: {index}, Animal: {animal}")


# TODO: Print squares of even numbers using list comprehensions
print([x**2 for x in nums if x % 2 == 0])
#

[0, 1, 4, 9, 16]
Index: 0, Animal: cat
Index: 1, Animal: dog
Index: 2, Animal: monkey
[0, 4, 16]


In [7]:
# Dictionaries
# TODO: Create a dictionary with keys = (cat, dog) and items = (cute,furry). Map 'cat' -> 'cute' and 'dog' -> 'furry'
petDict = {'cat': 'cute', 'dog': 'furry'}
print(petDict)
# TODO: Set an entry {'fish':'wet'}
petDict['fish'] = 'wet'
print(petDict)

# TODO: Remove the entry with key = cat
petDict.pop('cat', None)
print(petDict)


# TODO: Get the value of key "monkey" with a default value "EMPTY";
monkey_value = petDict.get('monkey', 'EMPTY')
print(monkey_value)

# TODO: Get an element with key= 'fish' and print it
print(petDict['fish'])

# TODO: Print all keys in dictionary
print(petDict.keys())

# TODO: Print all items in dictionary
print(petDict.items())


{'cat': 'cute', 'dog': 'furry'}
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
{'dog': 'furry', 'fish': 'wet'}
EMPTY
wet
dict_keys(['dog', 'fish'])
dict_items([('dog', 'furry'), ('fish', 'wet')])


In [8]:
# Sets
# TODO: Create a set with elements cat, dog and fish
petSet = {'cat', 'dog', 'fish'}


# TODO: Add monkey to the set
petSet.add('monkey')

# TODO: Remove fish from the set
petSet.discard('fish')
# TODO: Checks if "cat" is in the set
catFound = 'cat' in petSet
print("Cat in set =", catFound)
print(petSet)

Cat in set = True
{'monkey', 'cat', 'dog'}


# Numpy

In [9]:
#importing the numpy package
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
# TODO: Print the shape of the array
print(b.shape)

# TODO: Print an array of all zeros of shape(2,2)
print(np.zeros((2, 2)))

# TODO: Print an array of all ones of shape(1,2)
print(np.ones((1, 2)))

# TODO: Print an array of shape (3,3) with all elements in array = 7
print(np.full((3, 3), 7))

# TODO: Print an array filled with random values of shape (2,2)
print(np.random.random((2,2)))


(2, 3)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.32205854 0.65104218]
 [0.09193095 0.83724046]]


In [10]:
# ARRAY INDEXING
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# TODO: Use slicing to print out the subarray consisting of the first 2 rows and columns 1 and 2;

print(a[:2, 1:3])

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
# TODO: Print one element from each row of a using the indices in b
bIDX = 0
for aIDX in range(len(a)):
  print(a[aIDX][b[bIDX]])
  bIDX += 1


# TODO: Add 10 to one element from each row of a using the indices in b
bIDX = 0
for aIDX in range(len(a)):
  a[aIDX][b[bIDX]] += 10
  bIDX += 1
print(a)

[[2 3]
 [6 7]]
1
6
7
11
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [11]:
# Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])
# TODO: Print a numpy array of Booleans where elements of a are bigger than 2 ,shape=(3,2)
print(a>2)

# TODO: Print a rank 1 array (i.e. 1 dimension array) consisting of the elements of a that are bigger than 2 -> expected output [3,4,5,6]
print(a[a>2])
x = np.array([1, 2])
# TODO: Print data type of the array
print(type(x))
# TODO: Create an array [[1,2],[3,4]] with data type float32.
floatmtrx = np.array([[1, 2], [3, 4]], dtype=np.float32)


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
<class 'numpy.ndarray'>


In [12]:
# Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# TODO: Print elementwise addition using numpy function
print(np.add(x, y))
# TODO: Print elementwise difference using numpy function
print(np.subtract(x, y))

# TODO: Print elementwise multiplication using numpy function
print(np.multiply(x, y))
# TODO: Print elementwise division using numpy function
print(np.divide(x, y))

# TODO: Print elementwise square root using numpy function
print(np.sqrt(x))
print(np.sqrt(y))


[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [13]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

# TODO: Print Inner product of vectors x and y, v and w
print(np.dot(x,y))
print(np.dot(v,w))

# TODO: Print the product of x and v
print(np.dot(x,v))
# TODO: Print the product of x and y
print(np.dot(x,y))


[[19 22]
 [43 50]]
219
[29 67]
[[19 22]
 [43 50]]


In [14]:
x = np.array([[1,2],[3,4]])
# TODO: Print sum of all elements in array
print(np.sum(x))

# TODO: Print sum of elements in each row
print(np.sum(x, axis = 1))

# TODO: Print sum of elements in each column
print(np.sum(x, axis = 0))


10
[3 7]
[4 6]


In [15]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
# TODO: Create an empty matrix with the same shape as x and print
empty_matrix = np.zeros_like(v)
print(empty_matrix)

# TODO: Create an array y by adding the vector v to each row of the matrix x with an explicit loop
y = np.zeros_like(x)
for i in range(x.shape[0]):
    y[i, :] = x[i, :] + v
print(y)
# TODO: Add v to each row of x using broadcasting
y = x + v
# store the result in matrix y and print y
print(y)


[0 0 0]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [16]:
v = np.array([1,2,3,4])
# TODO: Reshape v to(2,2) using numpy function and print it
v = v.reshape((2, 2))
print(v)

[[1 2]
 [3 4]]
